
2022-08-28 10:08:00,690 Downloading and reading train artifact
Traceback (most recent call last):
  File "run.py", line 176, in <module>
    go(args)
  File "run.py", line 31, in go
    df = pd.read_csv(train_data_path, low_memory=False)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Users/fahadalqhtani/opt/anaconda3/envs/mlflow-daa49f50394a29b25be6bee5f42d6e77b27f556d/lib/python3.8/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 759, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 842, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 6612